# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on a macOS system.

variables:
  SCRIPTS_DIR: Scripts

stages:
  - test

##################
#    Test    #
##################

# Runs all the tests found in Package.swift defines as .testTarget()
run-swift-tests:
  stage: test
  cache:
    paths:
      - .build/
  tags:
    - swift
  script:
    - swift test
