#if !canImport(ObjectiveC)
import XCTest

extension ProcessPrettyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessPrettyTests = [
        ("test_run_sync_verbose", test_run_sync_verbose),
        ("test_run_sync", test_run_sync),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ProcessPrettyTests.__allTests__ProcessPrettyTests),
    ]
}
#endif
